theme: jekyll-theme-slate
# title: YOUR TITLE
description: YOUR DESCRIPTION
title: |\n
··Several lines of text,\n
··with some "quotes" of various 'types',\n
··and also a blank line:\n
··\n
··and some text with\n
····extra indentation\n
··on the next line,\n
··plus another line at the end.\n
